// <auto-generated />
using CountryPaths.Shared.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountryPaths.Shared.Migrations
{
    [DbContext(typeof(CountryPathsContext))]
    [Migration("20210221071932_initdb")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("CountryPaths.Shared.DB.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("XCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YCoordinate")
                        .HasColumnType("INTEGER");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CountryPaths.Shared.DB.CountryPath", b =>
                {
                    b.Property<int>("CountryLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("CountryLinkId");

                    b.ToTable("CountryPaths");
                });
#pragma warning restore 612, 618
        }
    }
}
